server:
  port: 8081
spring:
  application:
    name: "plazoleta"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"x
  profiles:
    include: null
  datasource:
    url: "jdbc:mysql://localhost:xxx/plazoleta_plaza_de_comidas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: "root"
    password: "12345678"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: "update"
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    url: "http://localhost:8080"
resilience4j:
  circuitbreaker:
    instances:
      obtenerUsuarioPorId:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
jwt:
  secret: "xxx"
springdoc:
  info:
    title: "API de microservicio de plazoleta"
    description: "Documentación de los endpoints para la gestión de la plazoleta"
twilio:
  account-sid: "xxx"
  auth-token: "xxx"
  from-number: "xxx"
